[fix] searxng toolkit import for tool initialization (#3424)
## Summary

Updated import from `from agno.tools.toolkit import Toolkit` to `from
agno.tools import Toolkit` since it was causing the incorrect
initialization of the tool causing an `AttributeError: 'Searxng' object
has no attribute 'include_tools'`

Fixes an issue I talked about in #3423 also

## Type of change

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Improvement
- [ ] Model update
- [ ] Other:

---

## Checklist

- [x] Code complies with style guidelines
- [x] Ran format/validation scripts (`./scripts/format.sh` and
`./scripts/validate.sh`)
- [x] Self-review completed
- [ ] Documentation updated (comments, docstrings)
- [ ] Examples and guides: Relevant cookbook examples have been included
or updated (if applicable)
- [x] Tested in clean environment
- [ ] Tests added/updated (if applicable)

---

## Additional Notes

Add any important context (deployment instructions, screenshots,
security considerations, etc.)

---------

Co-authored-by: ysolanky <yash@phidata.com>